#!/usr/bin/env bash

set -Eeuo pipefail

readonly PROFILE="${PROFILE_MODE:-base}"
readonly AUTO="${AUTO_APPLY:-0}"
readonly CONFIG_DIR="/etc/linux-optimizer"
readonly SYSCTL_FILE="${CONFIG_DIR}/sysctl-${PROFILE}.conf"
readonly LIMITS_FILE="${CONFIG_DIR}/limits.conf"
readonly SSH_FILE="${CONFIG_DIR}/sshd.conf"
readonly LOG_PREFIX="[${PROFILE}]"
readonly PROFILE_START="$(date +%s)"

info() { printf '\033[36m%s\033[0m %s\n' "$LOG_PREFIX" "$*"; }
success() { printf '\033[32m%s\033[0m %s\n' "$LOG_PREFIX" "$*"; }
warn() { printf '\033[33m%s\033[0m %s\n' "$LOG_PREFIX" "$*"; }
error() { printf '\033[31m%s\033[0m %s\n' "$LOG_PREFIX" "$*" >&2; }

stage() {
    local current="$1" total="$2" label="$3" now elapsed width filled empty
    now=$(date +%s)
    elapsed=$((now - PROFILE_START))
    width=24
    filled=$((current * width / total))
    empty=$((width - filled))
    printf '\033[36m[%d/%d]\033[0m [%s%s] %3d%%  %-38s \033[2m(%02dm%02ds)\033[0m\n' "$current" "$total" "$(printf '%*s' "$filled" '' | tr ' ' '=')" "$(printf '%*s' "$empty" '')" "$((current * 100 / total))" "$label" "$((elapsed / 60))" "$((elapsed % 60))"
}

require_root() {
    [[ "$EUID" -eq 0 ]] || { error "Les profils doivent etre lances en root."; exit 1; }
    [[ "${ID:-debian}" == debian ]] || { error "Ce profil est reserve a Debian."; exit 1; }
}

confirm() {
    local answer
    if [[ "$AUTO" == 1 ]]; then
        return 0
    fi
    read -r -p "$1 [y/N] " answer
    [[ "$answer" =~ ^[yY]$ ]]
}

has_role() {
    [[ ",$PROFILE," == *",$1,"* || "$PROFILE" == full ]]
}

backup_file() {
    local file="$1"
    if [[ -e "$file" || -L "$file" ]]; then
        cp -a -- "$file" "${file}.linux-optimizer.$(date +%Y%m%d-%H%M%S).bak"
    fi
}

write_config() {
    local file="$1" content="$2"
    mkdir -p "$CONFIG_DIR"
    backup_file "$file"
    printf '%b\n' "$content" > "$file"
    chmod 0644 "$file"
}

available_sysctl() {
    local key="$1" value="$2"
    sysctl -q "$key" >/dev/null 2>&1 && printf '%s = %s\n' "$key" "$value"
}

build_sysctl() {
    local file="$SYSCTL_FILE" file_max
    file_max=$(cat /proc/sys/fs/file-max 2>/dev/null || printf '1048576')
    {
        printf '# Generated by AxelL Linux Optimmisateur for profile %s\n' "$PROFILE"
        printf 'fs.file-max = %s\n' "$file_max"
        available_sysctl net.core.somaxconn 4096
        available_sysctl net.core.netdev_max_backlog 4096
        available_sysctl net.ipv4.tcp_syncookies 1
        available_sysctl net.ipv4.tcp_slow_start_after_idle 1
        available_sysctl net.ipv4.tcp_keepalive_time 600
        available_sysctl net.ipv4.tcp_keepalive_intvl 60
        available_sysctl net.ipv4.tcp_keepalive_probes 5
        available_sysctl net.ipv4.conf.default.rp_filter 2
        available_sysctl net.ipv4.conf.all.rp_filter 2
        available_sysctl vm.swappiness 10
        available_sysctl vm.vfs_cache_pressure 100
        if sysctl -n net.ipv4.tcp_allowed_congestion_control 2>/dev/null | tr ' ' '\n' | grep -qx bbr; then
            available_sysctl net.ipv4.tcp_congestion_control bbr
        else
            warn "BBR indisponible : conservation de l'algorithme TCP actuel."
        fi
        if sysctl -q net.core.default_qdisc >/dev/null 2>&1; then
            available_sysctl net.core.default_qdisc fq
        fi
        if has_role docker; then
            available_sysctl fs.inotify.max_user_instances 1024
            available_sysctl fs.inotify.max_user_watches 524288
        fi
        if has_role web; then
            available_sysctl net.core.somaxconn 8192
        fi
        if has_role pterodactyl; then
            available_sysctl net.ipv4.ip_forward 1
            available_sysctl net.ipv6.conf.all.forwarding 1
        fi
    } > "$file"
}

run_apt() {
    local label="$1" output_file pid frame=0 frames='|/-\\'
    shift
    output_file=$(mktemp /tmp/linux-optimizer-apt.XXXXXX)
    DEBIAN_FRONTEND=noninteractive apt-get -q "$@" >"$output_file" 2>&1 &
    pid=$!
    if [[ -t 1 ]]; then
        while kill -0 "$pid" 2>/dev/null; do
            printf '\r\033[36m  %s\033[0m %s' "${frames:frame%4:1}" "$label"
            sleep 0.15
            ((frame += 1))
        done
        printf '\r\033[2K'
    else
        printf '[....] %s\n' "$label"
    fi
    if ! wait "$pid"; then
        cat "$output_file" >&2
        rm -f "$output_file"
        error "Echec de l'etape APT : $label"
        return 1
    fi
    rm -f "$output_file"
    success "$label termine."
}

update_system() {
    run_apt "Mise a jour des index APT" update
    run_apt "Mise a jour des paquets Debian" -y upgrade
    if apt-cache policy linux-image-amd64 2>/dev/null | awk '$1 == "Candidate:" && $2 != "(none)" {found=1} END {exit !found}'; then
        run_apt "Mise a jour du noyau Debian si disponible" -y install --only-upgrade linux-image-amd64 linux-headers-amd64
    else
        warn "Paquet de noyau Debian generique indisponible : noyau actuel conserve."
    fi
}

install_base_packages() {
    local packages=(ca-certificates curl jq htop vim-tiny unzip rsync openssh-client)
    if [[ "$PROFILE" != full ]] && has_role app; then packages+=(python3 python3-venv nodejs npm); fi
    if [[ "$PROFILE" != full ]] && has_role web; then packages+=(nginx); fi
    if [[ "$PROFILE" != full ]] && has_role docker; then packages+=(uidmap); fi
    run_apt "Installation des outils serveur" -y install "${packages[@]}"
}

apply_sysctl() {
    info "Preparation des reglages noyau adaptes au profil."
    mkdir -p "$CONFIG_DIR"
    backup_file "$SYSCTL_FILE"
    build_sysctl
    if ! sysctl --load="$SYSCTL_FILE" >/tmp/linux-optimizer-sysctl.$$ 2>&1; then
        cat /tmp/linux-optimizer-sysctl.$$ >&2
        rm -f /tmp/linux-optimizer-sysctl.$$ "$SYSCTL_FILE"
        error "Les reglages noyau n'ont pas ete appliques."
        return 1
    fi
    rm -f /tmp/linux-optimizer-sysctl.$$
    success "Reglages noyau appliques dans $SYSCTL_FILE."
}

apply_limits() {
    local nofile
    nofile=$(( $(ulimit -n 2>/dev/null || printf '1024') < 65536 ? 65536 : $(ulimit -n 2>/dev/null || printf '1024') ))
    write_config "$LIMITS_FILE" "# Limits managed by AxelL Linux Optimmisateur\n* soft nofile $nofile\n* hard nofile $nofile"
    success "Limite nofile configuree a $nofile, sans modifier /etc/profile."
}

apply_ssh() {
    local sshd_bin="$(command -v sshd || true)"
    [[ -n "$sshd_bin" ]] || { warn "sshd absent : configuration SSH ignoree."; return 0; }
    write_config "$SSH_FILE" $'# Managed by AxelL Linux Optimmisateur\nUseDNS no\nTCPKeepAlive yes\nClientAliveInterval 300\nClientAliveCountMax 2\nAllowTcpForwarding no\nGatewayPorts no\nPermitTunnel no\nX11Forwarding no'
    mkdir -p /etc/ssh/sshd_config.d
    backup_file /etc/ssh/sshd_config.d/99-linux-optimizer.conf
    cp "$SSH_FILE" /etc/ssh/sshd_config.d/99-linux-optimizer.conf
    if ! "$sshd_bin" -t; then
        rm -f /etc/ssh/sshd_config.d/99-linux-optimizer.conf
        error "Configuration SSH invalide : aucun redemarrage effectue."
        return 1
    fi
    if confirm "Redemarrer SSH pour appliquer le durcissement maintenant ?"; then
        systemctl reload ssh 2>/dev/null || systemctl reload sshd
        success "SSH valide et recharge."
    else
        warn "Configuration SSH installee mais non rechargee."
    fi
}

show_ports() {
    info "Ports actuellement en ecoute :"
    ss -H -lntu 2>/dev/null | awk '{print "  " $1 " " $5}' | sort -u || true
    if command -v docker >/dev/null 2>&1; then
        info "Ports Docker publies :"
        docker ps --format '  {{.Names}}: {{.Ports}}' 2>/dev/null || true
    fi
}

apply_firewall() {
    show_ports
    if systemctl is-active --quiet firewalld 2>/dev/null; then
        warn "firewalld est actif : aucune installation ou purge de pare-feu ne sera effectuee."
        return 0
    fi
    if ! command -v ufw >/dev/null 2>&1; then
        warn "UFW absent. Installez-le et definissez vos regles metier avant de revenir ici."
        return 0
    fi
    warn "Le script ne peut pas deduire quels ports applicatifs doivent etre publics."
    if confirm "Ajouter uniquement le port SSH detecte et 80/443 a UFW ?"; then
        local ssh_port
        ssh_port=$(sshd -T 2>/dev/null | awk '$1 == "port" {print $2; exit}' || printf '22')
        ufw allow "${ssh_port}/tcp"
        ufw allow 80/tcp
        ufw allow 443/tcp
        ufw reload
        success "Regles minimales ajoutees ; les ports Docker/Pterodactyl restent a definir explicitement."
    else
        warn "Pare-feu laisse inchange."
    fi
}

apply_swap() {
    if swapon --show --noheadings 2>/dev/null | grep -q .; then
        success "Swap deja active : aucune taille imposee."
        return 0
    fi
    warn "Aucune swap active detectee. Sa taille depend du workload et ne sera pas imposee automatiquement."
    if confirm "Creer une swap de 1 Gio a /swapfile ?"; then
        fallocate -l 1G /swapfile
        chmod 600 /swapfile
        mkswap /swapfile >/dev/null
        swapon /swapfile
        grep -qF '/swapfile none swap sw 0 0' /etc/fstab || printf '/swapfile none swap sw 0 0\n' >> /etc/fstab
        success "Swap de 1 Gio activee."
    fi
}

profile_description() {
    if [[ "$PROFILE" == full ]]; then
        printf 'Optimisation complete automatique pour serveur professionnel.'
    elif [[ "$PROFILE" == base || "$PROFILE" == *,* || "$PROFILE" == docker || "$PROFILE" == web || "$PROFILE" == app || "$PROFILE" == pterodactyl || "$PROFILE" == keyhelp ]]; then
        printf 'Optimisation combinee des roles : %s.' "$PROFILE"
    else
        error "Profil inconnu : $PROFILE"
        return 1
    fi
}

main() {
    require_root
    profile_description
    info "$(profile_description)"
    printf '\n'
    if [[ "$AUTO" == 1 ]]; then
        warn "Mode automatique : les etapes du profil seront appliquees sans question intermediaire."
    else
            info "Apercu : systeme, noyau, paquets, sysctl, limites nofile, SSH, pare-feu et swap seront traites."
    fi
    show_ports
    if [[ "${1:-}" == "--audit" || "${1:-}" == "--dry-run" ]]; then
        success "Mode audit : aucune modification."
        return 0
    fi
    confirm "Appliquer le profil $PROFILE ?" || { warn "Operation annulee."; return 0; }
    stage 1 7 "Mise a jour du systeme et du noyau"
    update_system
    stage 2 7 "Installation des outils du profil"
    install_base_packages
    stage 3 7 "Reglages noyau et reseau"
    apply_sysctl
    stage 4 7 "Limites de fichiers pour les services"
    apply_limits
    stage 5 7 "Validation et durcissement SSH"
    if confirm "Appliquer le durcissement SSH ?"; then apply_ssh; fi
    stage 6 7 "Analyse du pare-feu et des ports"
    if confirm "Analyser puis proposer les regles pare-feu ?"; then apply_firewall; fi
    stage 7 7 "Verification de la swap"
    apply_swap
    success "Profil $PROFILE termine."
}

main "$@"
